name: "food_truck_finder_user_app"
description: "Find your nearest food truck or restaurant and review their foods."

publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  go_router: ^15.1.2
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  flutter_svg: ^2.1.0
  google_maps_flutter: ^2.12.1
  firebase_core: ^3.13.1
  permission_handler: ^12.0.0+1
  location: ^8.0.0
  chips_choice: ^3.0.1
  image_picker: ^1.1.2
  flutter_rating_stars: ^1.1.0
  google_sign_in: ^6.3.0
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  timeago: ^3.7.1
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  geolocator: ^14.0.0
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  firebase_messaging: ^15.2.6
  flutter_html: ^3.0.0
  app_tracking_transparency: ^2.0.6+1
  sign_in_with_apple: ^7.0.1
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  build_runner: ^2.4.6
  intl_utils: ^2.8.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5

flutter_launcher_icons:
  image_path_android: "assets/icons/nine_i.png"
  image_path_ios:  "assets/icons/nine_i.png"
  android: true     
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/map-marker.png
    - assets/icons/
    - assets/svgs/
    - assets/map_json/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/localization/l10n
  output_dir: lib/generated
  use_deferred_loading: false
